blank_issues_enabled: true
contact_links:
  - name: Questions and show & tell
    url: https://github.com/dbl8005/repos-and-dungeons/discussions
    about: Share your dungeon, ask questions, swap timelapses.
